### ISSUE TITLE
"includeHost: false" not working

### ISSUE THREAD

**Issue by AlexandreKilian** [Bukashk0zzz/LiipImagineSerializationBundle#1] opened 2016-06-20 09:44 UTC
Hello,

I tried to configure the bundle according to the documentation, everything worked fine until I tried some configurations. For example it doesn't change anything if I set includeHost to false, the host still is attached to the URL. I checked if it works if I define multiple filters, but with that I get 

> Notice: Array to string conversion

**Comment by Bukashk0zzz** [comment] 2016-06-20 09:54
Hi,

I checked and in bundle are no tests for case you described. So I think there are some bug. 
Can you fix it and send pull request? If no I can do this but not today. 

I think I will have time on Wednesday.

**Comment by Bukashk0zzz** [comment] 2016-06-24 12:51
I created tests with configuration that you described and all works like expected.
https://github.com/Bukashk0zzz/LiipImagineSerializationBundle/blob/master/Tests/EventListener/JmsSerializeListenerTest.php#L161

What version of Symfony you use?
You try to serialize VichUploader field?
Did you store url or name of file in Entity that you serialize?
Can you show example of configuration, Entity and data that you serialize?

**Comment by AlexandreKilian** [comment] 2016-06-27 13:33
I'm running symfony 2.8, with jms serializer and I'm serializing the correct field:

```
  /**
     *
     * @Vich\UploadableField(mapping="media_element", fileNameProperty="src")
     * @JMS\Exclude()
     * @var File
     */
     private $file;
    /**
     * @var string
     *
     * @ORM\Column(name="src", type="string", length=255, nullable=true)
     * @Bukashk0zzz\LiipImagineSerializableField(filter={"cover","main_image"}, vichUploaderField="file")
     * @JMS\Groups({"list","edit"})
     */
    public $src;
```

it doesn't work with arrays, this is where I get an exception. This here works, but the includeHost still isn't working

```
  /**
     * @var string
     *
     * @ORM\Column(name="src", type="string", length=255, nullable=true)
     * @Bukashk0zzz\LiipImagineSerializableField(filter="cover", vichUploaderField="file")
     * @JMS\Groups({"list","edit"})
     */
    public $src;
```

**Comment by AlexandreKilian** [comment] 2016-06-29 13:02
I found the solution to the first problem:

`* @JMS\Type("array")` fixes the serialization problem... maybe I'll find the problem with the included host too

**Comment by AlexandreKilian** [comment] 2016-06-29 14:25
I've looked a bit into the code and found a problem in `JmsPreSerializeListener` 
Without the option virtualField, the serialization ignores other options like _vichUploaderField_, the host is added every time

Without virtualField, the configuration includeHost is being checked, and the path is being generated by the cacheManager. The liipCacheManager itself adds the host. I actually even managed to have the host being added twice, once by liip, and then once more by this bundle.

I haven't totally figured out, where liipimagingebundle is adding the host, but that's not a concern for this bundle, just thought I'd share what I found

**Comment by wuestkamp** [comment] 2016-07-24 19:54
Same here, host always included. With or without `virtualField` specified

**Comment by wuestkamp** [comment] 2016-07-25 18:14
I think the issue is that in `JmsSerializeListenerAbstract:serializeValue()` the `this->cacheManager->getBrowserPath` always returns the full path

**Comment by Bukashk0zzz** [comment] 2016-08-19 13:23
For now how I understand all works correct.

You can use
- includeHost: false // To not generating url with host for vichUploader fields
- includeOriginal: false // To not adding host url to original value for vichUploader fields

If you don't want include host in thumbnails you need remove host in liip imagine bundle.

If I correct I will close this issue.

**Closed as completed** 2016-11-04 13:31 UTC
Labels: wontfix
